### ISSUE TITLE
CPU mode speed problem

### ISSUE THREAD

**Issue by bluekingdom** [luoyetx/mini-caffe#13]
I found mini-caffe running speed is slower than speed of official version in CPU mode. It blame to conv layer in figure below. Can anyone give some tip that why conv layer will be slow?

left: mini-caffe time. right: official caffe time. run in win10 vs2013.

![ng4 t5q7yeb3xk8laddxhm8](https://cloud.githubusercontent.com/assets/6635281/22688749/9bc33a96-ed68-11e6-9274-f31decf0713c.png)

**Comment by luoyetx** [comment]
@bluekingdom I'll look into the implement of convolution layer. The code in this repo is based on [BVLC/caffe@f28f5ae](https://github.com/BVLC/caffe/tree/f28f5ae2f2453f42b5824723efc326a04dd16d85), which is a half year ago, around 2016/06.

**Comment by luoyetx** [comment]
@bluekingdom Would you mind update mini-caffe to the last commit. It supports Win64 now. Did you test with Win32 or Win64?

**Comment by bluekingdom** [comment]
@luoyetx thx~ 
I test with win64, and i clone the mini-caffe in 3 day age. 
I also test in GPU mode, and the speed is the same as official version.

**Comment by luoyetx** [comment]
@bluekingdom The layer code in Caffe doesn't change for a long time, see [here](https://github.com/BVLC/caffe/tree/master/src/caffe/layers). The cpu code in this repo should be the same as official Caffe. It seems not only the convolution is slower than the official Caffe, but all layers are slower. Could you provide more detail about your test?

- Debug or Release mode?
- How many threads does OpenBLAS use?

**Comment by bluekingdom** [comment]
@luoyetx I test in x64 Release mode. 
I don't know how to set number of threads OpenBLAS use, please get me a tip.....
and I observe that the cpu usage of mini-caffe is higher than official caffe even through test code is identical.

**Comment by luoyetx** [comment]
@bluekingdom You can set `OPENBLAS_NUM_THREADS`, see [here](https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded). But, I don't think it's the reason for slow down.

**Comment by bluekingdom** [comment]
@luoyetx Thx again~ 
I have been adding some layers related to ssd in mini-caffe, maybe change something i am not aware of. I will check again.

**Comment by bluekingdom** [comment]
I clone a new repo and run run_net.exe to test nin model. use 1 thread in openblas. `openblas_set_num_threads( 1 );`

![image](https://cloud.githubusercontent.com/assets/6635281/22776479/bef2d2dc-eeea-11e6-87f5-9ba6199802ce.png)

My computer profile show above:
![image](https://cloud.githubusercontent.com/assets/6635281/22776696/9d9324ba-eeeb-11e6-9564-fe7ac5716be6.png)

If anyone test the nin net and faster than me, please tell me how to configue. thx~~

**Comment by luoyetx** [comment]
@bluekingdom You output is strange. Did you download the model from [luoyetx/misc](https://github.com/luoyetx/misc)? Since the nin model is very small, it only costs about 120ms to run on my PC in CPU mode. You may turn off the IO print and test it again.

**Comment by bluekingdom** [comment]
@luoyetx Thx~
I test model from misc and turn off the io. The result show above:
![image](https://cloud.githubusercontent.com/assets/6635281/22815698/10b4edaa-ef98-11e6-8be7-a83f8392eb67.png)

It run in CPU Release x64 mode, use one thread in openblas.

I test a new repo and don't edit anything except add `openblas_set_num_threads( 1 )` in Net::Init().
I can not figure out reason for running slow.....

**Comment by luoyetx** [comment]
@bluekingdom I have no idea. I also test with `openblas_set_num_threads(1)`

without `openblas_set_num_threads(1)`
![1](https://cloud.githubusercontent.com/assets/2768843/22817662/98196248-efa3-11e6-8e36-257544cc44a5.png)

with `openblas_set_num_threads(1)`
![t1](https://cloud.githubusercontent.com/assets/2768843/22817671/a595ec8e-efa3-11e6-8791-b6ca7a504c34.png)

Actually, the difference is very small. My PC is below.
![p](https://cloud.githubusercontent.com/assets/2768843/22817706/df07267c-efa3-11e6-95f0-87f3b2e14468.png)

**Comment by matthill** [comment]
I'm seeing similar differences in CPU processing speed.  Using the same network and weights on the latest version of Caffe vs Mini-Caffe, both linked against OpenBlas.  I set the following env var before running:
export OPENBLAS_NUM_THREADS=1

Mini-Caffe time: 0.223066 s
Caffe time: 0.136007 s

**Comment by matthill** [comment]
Adding:
set(CMAKE_BUILD_TYPE Release)

To the top of CMakeLists.txt resolved the issue for me.  Benchmark again:

Mini-caffe time: 0.130869 s
Caffe time: time: 0.136407 s

Average is actually somewhat consistently a few milliseconds faster on Mini-Caffe, interestingly enough.

Very nice library btw.  I did something similar to get Caffe compiled on Windows, but your changes are cleaner.  Nice tweaks to the API as well.

**Comment by luoyetx** [comment]
@matthill Thanks for the testing. I think we need to pass `-DCMAKE_BUILD_TYPE=Release` to cmake when build on Linux. It seems the default build type is Debug. For Visual Studio, we don't need to do that.

**Comment by luoyetx** [comment]
@bluekingdom  If you still suffer from the performance, consider update Mini-Caffe and run tests, then you can get `profile.json` under build folder, Open it in google chrome using chrome://tracing to see what's wrong.

![profile](https://cloud.githubusercontent.com/assets/2768843/23301487/19555020-fac5-11e6-9850-459c4e37ceb8.png)

**Comment by luoyetx** [comment]
I'll close this issue for now, feel free to reopen it if anyone still suffers from CPU performance.

**Comment by bluekingdom** [comment]
@luoyetx It seem the performance problem disappear when i update new Mini-caffe.
And the profile is very useful !
thx a lot~~~

**Comment by luoyetx** [comment]
@bluekingdom currently the Profiler has a bug, the time stamp is not accuracy using VC12 compiler, it will be fixed when this commit 1db763b merged.

**Comment by ChaoWU-USTC** [comment]
@luoyetx 
How can I turn off the IO print of mini-caffe, such as "syncedmem.cpp:214: [CPU] Requested 2.5 K, Get 2.5 K"
Should I comment the DLOG sentences in src code? Or maybe there are some other methods?

**Comment by luoyetx** [comment]
@ChaoWU-USTC build with Release mode, then `DLOG` will print nothing.

**Comment by ChaoWU-USTC** [comment]
@luoyetx That works, thx a lot!

**Comment by mychina75** [comment]
@bluekingdom
Have you finished adding SSD layers for this repository?
