### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Thanh-Binh** [luoyetx/mini-caffe#2]
I have the following error:
e:\Projects\DeepLearning\mini-caffe-master\src\caffe\util\upgrade_proto.cpp(196): error C2660: 'caffe::ConvolutionParameter::set_pad': Function does not accept one input argumente

Could you please help me?

**Comment by luoyetx** [comment]
@Thanh-Binh which compiler do you use?

**Comment by Thanh-Binh** [comment]
I use VisualStudio 2013 64bits.
Here I think that your ser_pad() expects 2 input arguments, while puting only one.

**Comment by luoyetx** [comment]
you should use vs2013 and build x86

**Comment by zhly0** [comment]
@luoyetx hi ，luoyetx,thanks for your nice work.your 3party lib is x64，and you said use vs2013 and build x86,the 3 party lib need to complie from the beginning?

**Comment by luoyetx** [comment]
if you want x86 build, checkout the pre-compiled 3rdparty libraries [here](https://github.com/luoyetx/mini-caffe/releases/tag/v0.4.0).

**Comment by zhly0** [comment]
@luoyetx ，wonderful，thank you！
