### ISSUE TITLE
怎么设置多线程运行？

### ISSUE THREAD

**Issue by wuqiangch** [luoyetx/mini-caffe#22]
@luoyetx 如果要多线程运行，在编译和运行的时候怎么设置，谢谢！！

**Comment by luoyetx** [comment]
@wuqiangch 多线程加速只能通过 OpenBLAS 来实现，可以参考[这里](https://github.com/xianyi/OpenBLAS/wiki/Faq#multi-threaded)

**Comment by wuqiangch** [comment]
@luoyetx 谢谢，如果又有10张图像提取特征，我使用openmp 提取特征时，和单张提取的特征不一样，难道只能单张图像多线程提取特征吗？

**Comment by luoyetx** [comment]
@wuqiangch Net 对象不是线程安全的，不能在多个线程下同时 Forward

**Comment by ChaoWU-USTC** [comment]
@luoyetx 
你好！多个线程使用各自线程私有的Net对象，同时进行Forward，是否存在问题？

**Comment by luoyetx** [comment]
@ChaoWU-USTC 这样子没有问题的

**Comment by ChaoWU-USTC** [comment]
@luoyetx 好的，谢谢！
