### ISSUE TITLE
double free or corruption (!prev): 0x00de2b60 *** Abortedn 

### ISSUE THREAD

**Issue by zhangyifu2016** [luoyetx/mini-caffe#3]
Hi, I get a problem when I run your mini caffe example on arm(raspberry pi 3 b):

./ex
detection time: 346.662
face1 keypoints time: 88.37
face2 keypoints time: 83.353
face3 keypoints time: 83.481
face4 keypoints time: 83.531
face5 keypoints time: 83.623
detect number: 5
sleep  time: 3000.29
*** Error in `./ex': double free or corruption (!prev): 0x019fc6f0 ***
Aborted

it occurs in main function when return;

I also have ran MTCNN with your mini caffe, but facing the same problem:

pi@raspberrypi:~/MTSrc/build $ ./MTCNN ../ ../test2.jpg
Detect 431X450 Time Using CPU: 2597.32
*** Error in `./MTCNN': double free or corruption (!prev): 0x00de2b60 ***
Aborted

How to solve it?

**Comment by luoyetx** [comment]
I only use this project on windows with VC12. I don't know what compiler you use in your pi. I'm suppose you are using Linux, then please consider the official Caffe repo.

The double free error I think is not throw from Caffe's code. You should debug the code and find out which line in the code throw this error.

**Comment by zhangyifu2016** [comment]
Using the same codes, running on x86 linux has no problem. I think the problem is the different of compiling tools. I use linaro's arm-linux-gnueabihf. 
well, it's not a fatal error.
Thank you.
