### ISSUE TITLE
problem when compiling mini-Caffe

### ISSUE THREAD

**Issue by ligongzheng** [luoyetx/mini-caffe#32]
I install the miniCaffe with the commends listed in readme.md and my OS is ubuntu.Then I encounter a problem like this:
[ 96%] Linking CXX executable run_net
/usr/bin/ld: CMakeFiles/run_net.dir/tests/run_net.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/run_net.dir/build.make:95: recipe for target 'run_net' failed
make[2]: *** [run_net] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/run_net.dir/all' failed
make[1]: *** [CMakeFiles/run_net.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I know nothing about cmake. Could anyone help me to solve this problem ?

**Comment by luoyetx** [comment]
add `pthread` library in this line https://github.com/luoyetx/mini-caffe/blob/master/tests/tests.cmake#L3

**Comment by ligongzheng** [comment]
I add the library as you said:
# cpp                                                                       
  2 add_executable(run_net ${CMAKE_CURRENT_LIST_DIR}/run_net.cpp)
  3 target_link_libraries(run_net caffe -lprotobuf protobuf   pthread)
  4 
  5 # c
  6 add_executable(run_net_c ${CMAKE_CURRENT_LIST_DIR}/run_net.c)
  7 target_link_libraries(run_net_c caffe -lprotobuf protbuf  pthread)

But I still have the problem:
[ 93%] Built target caffe
[ 94%] Linking CXX executable run_net
libcaffe.so: undefined reference to `google::protobuf::internal::RegisterAllTypes(google::protobuf::Metadata const*, int)'
libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarintSizeAsIntFallback()'
libcaffe.so: undefined reference to `google::protobuf::internal::InitProtobufDefaults()'
....
Or I need to add the library path (-L) in target_link_libraries ?

**Comment by ligongzheng** [comment]
I have solved the problem by this:
  1 # cpp                                                                       
  2 include(FindProtobuf)
  3 find_package(Protobuf REQUIRED)
  4 include_directories(${PROTOBUF_INCLUDE_DIR})
  5 
  6 add_executable(run_net ${CMAKE_CURRENT_LIST_DIR}/run_net.cpp)
  7 target_link_libraries(run_net caffe  ${Boost_FILESYSTEM_LIBRARY} ${Boost_SYS    TEM_LIBRARY} ${PROTOBUF_LIBRARY}   pthread)
  8 
  9 # c
 10 add_executable(run_net_c ${CMAKE_CURRENT_LIST_DIR}/run_net.c)
 11 target_link_libraries(run_net_c caffe ${PROTOBUF_LIBRARY}  pthread)
