### ISSUE TITLE
A bug in blog.cpp

### ISSUE THREAD

**Issue by ligongzheng** [luoyetx/mini-caffe#35]
In the blob.cpp: reshape function,we should allocate shape.size*sizeof(int) instead of KMaxBlobAxes*sizeof(int).
Is that right ?

**Comment by luoyetx** [comment]
cache the shape data memory so that we don't need to realloc the memory when shape changes.

**Comment by ligongzheng** [comment]
Could I have your WeiChat so that I can consult with you ?

**Comment by ligongzheng** [comment]
But if the size after reshped  bigger than KMaxBlobAxes, it will realloc or not ?I print the KMaxBlobAxes and the result is 32 .In my thought,if I reshape a bigger size like (1,1,1,33),there should be a core dump.I try it but there is no mistake about memory.What's the matter ??Thank you in advanced.

**Comment by luoyetx** [comment]
kMaxBlobAxes is the maximum number of shape dimension
