### ISSUE TITLE
How to  download the caffemodel file ?

### ISSUE THREAD

**Issue by ligongzheng** [luoyetx/mini-caffe#36]
I want to run the example in the example fold,But after compiled the program said no caffemodel.How can I download this caffemodel file?

**Comment by luoyetx** [comment]
The model file is downloaded by this [line](https://github.com/luoyetx/mini-caffe/blob/master/travis.sh#L13-L18). They are in repo [luoyetx/misc](https://github.com/luoyetx/misc).
