### ISSUE TITLE
为什么要去模板？

### ISSUE THREAD

**Issue by ligongzheng** [luoyetx/mini-caffe#37]
作者您好：
       在caffe里面基本上所有的类都是模板类，但是在minicaffe的实现中，把模板都去掉了，采用的是float的数据类型。所以我想请教下：为什么要去模板化？c++的模板是编译时的多态，因此模板的存在不会影响程序运行时的性能。minicaffe应该算是caffe的前向传播版本，去掉模板本身也是一项工作，但是这个工作好像也不能带来性能的提升。所以想问下您，去模板是出于一个什么样的想法？
      最后，非常感谢您在前面几次的耐心回答！

**Comment by luoyetx** [comment]
去掉 double 类型，可以减小生成的库文件大小
