### ISSUE TITLE
How to stop printing LOG(INFO) in mcaffe?

### ISSUE THREAD

**Issue by ChaoWU-USTC** [luoyetx/mini-caffe#38]
When using minicaffe in my program, it continuously print LOG(INFO) message like this 
"""
[18:07:54] ~/GitHub/mini-caffe/src/util/upgrade_proto.cpp:35: Attempting to upgrade input file specified using deprecated input fields: ./config/deploy.prototxt
[18:07:54] ~/GitHub/mini-caffe/src/util/upgrade_proto.cpp:38: Successfully upgraded file specified using deprecated input fields.
[18:07:54] ~/GitHub/mini-caffe/src/util/upgrade_proto.cpp:40: Note that future Caffe releases will only support input layers and not input fields.
"""
These messages are not useful for me now, and slow down the whole program running.

I have tried some methods to change GLOG level, such as  set GLOG_minloglevel to 2, etc
But the printing is still the same.

So I  wonder how to forbid this print screen, without modifying src code of mini-caffe.

**Comment by luoyetx** [comment]
mini-caffe doesn't use glog. You can easily remove these logging message by comment the code in `mini-caffe/src/util/upgrade_proto.cpp`

**Comment by luoyetx** [comment]
As I realize that you don't want to change the source code of mini-caffe, the printed log message indicate that your deploy.prototxt use deprecated input fields. mainly like below

```
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 224
  dim: 224
}
```

use something like below should avoid the upgrade.

```
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param {
    shape: {
      dim: 1
      dim: 3
      dim: 224
      dim: 224
    }
  }
}
```

**Comment by ChaoWU-USTC** [comment]
@luoyetx 
Yes, deploy.prototxt is much like the one you present.
I have tried the second solution. It works. Thank you!
