### ISSUE TITLE
宏REGISTER_LAYER_GREATOR怎么理解？

### ISSUE THREAD

**Issue by ligongzheng** [luoyetx/mini-caffe#39]
宏REGISTER_LAYER_GREATOR从定义上看好像是申明了一个静态的函数，但是我没有找到这个静态函数的具体实现，只是见到这个宏产生的静态函数会在层的creator创建后会被调用，百思不得其解，还请作者帮忙解答，谢谢！

**Comment by luoyetx** [comment]
@ligongzheng 看一下这篇[博客](https://luoyetx.github.io/2016/02/reading-caffe-3/#reading-caffe-3)吧。
