### ISSUE TITLE
how to use GPU accelerate ?

### ISSUE THREAD

**Issue by QiYueFeiXue** [luoyetx/mini-caffe#43]
Hello, I use command  "cmake .. -DUSE_CUDA=ON -DUSE_CUDNN=ON"   to use gpu,   but only have a little speed up, not same as caffe. This is the result:

minicaffe   cpu :     51 ms.    gpu:  44ms
caffe    cpu:   78ms         gpu:    9ms
I know caffe to use gpu should add "caffe.set_mode_gpu()" in source file, how about minicaffe ?
Do you make opt in forward_cpu_gemm , why you program run fast than caffe ?
Thank you!

**Comment by luoyetx** [comment]
I optimize some layer implementation on CPU, so it's faster than the official Caffe on CPU side.

To use GPU, I suppose you use Python, take look at [this function](https://github.com/luoyetx/mini-caffe/blob/master/python/minicaffe/base.py#L118). For C/C++ API, take look at [this example](https://github.com/luoyetx/mini-caffe/blob/master/example/r-fcn/main.cpp)

**Comment by QiYueFeiXue** [comment]
Thank you ! This help me !

**Comment by luoyetx** [comment]
@QiYueFeiXue How's the performance for GPU. I think Mini-Caffe will be slight faster than Official Caffe.

**Comment by QiYueFeiXue** [comment]
However, in minicaffe GPU version is  slight lower than  Official Caffe.
I run 100 times, this is the average results:
minicaffe: 10.67ms      caffe: 8.84ms

**Comment by luoyetx** [comment]
It's much slower than the official Caffe, there might be same memory issue with the Memory Optimization implement. I will take a look at this. You can use the Profiler in Mini-Caffe to profile the detail performance of your network. Refer to this [python code](https://github.com/luoyetx/mini-caffe/blob/master/python/tests/test.py#L42-L61) and this [doc](https://github.com/luoyetx/mini-caffe/blob/master/profile.md).

**Comment by QiYueFeiXue** [comment]
Thank you ! I will try it!
