### ISSUE TITLE
How to install mini-caffe's gpu model  in TK1?

### ISSUE THREAD

**Issue by QiYueFeiXue** [luoyetx/mini-caffe#45]
I Know caffe could be installed in TK1, but when I install mini-caffe hit this issue:

/usr/lib/gcc/arm-linux-gnueabihf/4.8/include/stddef.h(432): error: identifier "nullptr" is undefined

I tried to solve this problem by add :  list(APPEND CUDA_NVCC_FLAGS --compiler-options "-std=c++03")
to Cuda.cmake but hit this issue:

/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

**Comment by luoyetx** [comment]
you need to turn on C++11 flag for gcc `-std=c++11`

**Comment by QiYueFeiXue** [comment]
是的，但是还会有些接口不兼容问题，导致编译出错。例如：参数个数不一致，cuda8.0定义了新类型。。。。

**Comment by QiYueFeiXue** [comment]
需要在Cuda.cmake中设置nvcc 编译选项 -std=c++11
TK1 支持最高cuda6.5，与cuda8.0 有些不兼容
