### ISSUE TITLE
can't find caffe API !

### ISSUE THREAD

**Issue by QiYueFeiXue** [luoyetx/mini-caffe#46]
In minicaffe I couldn't find c++ API like this: net->input_blobs() , net->output_blobs(). In fact, I need this API;

**Comment by luoyetx** [comment]
You should know your input and output blob names, then you can get these blobs by their name.  API  `net->input_blobs()`, `net->output_blobs()` is deleted.

**Comment by QiYueFeiXue** [comment]
Thank you!
