### ISSUE TITLE
How to add a new layer?

### ISSUE THREAD

**Issue by CBIR-LL** [luoyetx/mini-caffe#47]
Thank you for sharing the code. Could you tell me how to add a new layer in min-caffe? Is it the same as caffe?

**Comment by luoyetx** [comment]
It's the same as Official Caffe. Please refer to [proposal_layer.hpp](https://github.com/luoyetx/mini-caffe/blob/master/src/layers/proposal_layer.hpp). The default data type is float.

**Comment by CBIR-LL** [comment]
Thanks for your reply. If I use the code for classification task, then i need to get the final layer values (type: Softmax). The following code is right?
`
vector<float> get_values(layer_values->count());
	for (int i = 0; i < layer_values->count(); i++)
	{
		float &get_value = get_values[i];
		get_value = layer_values->data_at(0, i, 0, 0);####?
		cout << "get_value:" << get_value << endl;
	}
`

**Comment by luoyetx** [comment]
Assume you have the net definition like below
```
layer {
  name: "prob-layer"
  type: "Softmax"
  bottom: "score"
  top: "prob"
}
```

Then you should get the output from Blob `prob`.

```cpp
shared_ptr<Blob> prob = net->blob_by_name("prob");
for (int i = 0; i < prob->count(); i++) {
...
}
```

**Comment by luoyetx** [comment]
@CBIR-LL For more details, Please refer to [examples](https://github.com/luoyetx/mini-caffe/blob/master/example)

**Comment by CBIR-LL** [comment]
Thanks. I'll take a good look at your examples.
