### ISSUE TITLE
How to use android mini-caffe?

### ISSUE THREAD

**Issue by QiYueFeiXue** [luoyetx/mini-caffe#49]
Hello, I'm a fresher in android develop and I have developed some neural networks used c++ program language in x86\ubuntu OS. Now I have build mini-caffe to android, I want to know if my c++ programs needed modify.
Thank you!

**Comment by luoyetx** [comment]
You can refer to [luoyetx/WhatsThis](https://github.com/luoyetx/WhatsThis). The origin repo is using MXNet, I switch the backend to mini-caffe.

**Comment by QiYueFeiXue** [comment]
I saw you use mini-caffe API in  java, but I want to know could I use mini-caffe API in C++. In the end generated a .so library Used for android.
Thank you !

**Comment by luoyetx** [comment]
Yes, you can. I think you can add API just like I did in [src/jni/jni.c](https://github.com/luoyetx/mini-caffe/blob/master/src/jni/jni.c). Then wraps the API in Java.

**Comment by QiYueFeiXue** [comment]
谢谢你的回答，我用mini-caffe c++ 接口写了某个神经网络NN， 我想问能不能不修改NN代码，直接交叉编译成动态库，然后封装接口，给android使用。

**Comment by luoyetx** [comment]
android 端应该是得用 jni 来调用 C++ 代码，所以你至少得封一层 Java 和 C++ 的 API 吧

**Comment by QiYueFeiXue** [comment]
感谢你的回答!
我想问清楚， 对于我原先的NN代码，仍然使用mini-caffe C++ API， 然后使用jni 封装我的NN 代码， 提供给Java 使用。 这个意思吗？

**Comment by QiYueFeiXue** [comment]
谢谢您的耐心解答，问题已解决。 将mini-caffe编译为android版本， 原先使用mini-caffe C++ API 无需修改。 多谢！！
