### ISSUE TITLE
多线程问题

### ISSUE THREAD

**Issue by zhly0** [luoyetx/mini-caffe#54]
你好,问下在mini-caffe中common.hpp中有Caffe这个类,为什么找了半天没看到在哪里有用啊,还有这个mini-caffe的多线程是怎么样的啊?就是在不同的线程中调用用CaffeNetCreate初始化了的net会怎么样,会和https://github.com/BVLC/caffe/issues/4595 中一样吗?

**Comment by luoyetx** [comment]
Caffe 这个类是 thread local 的单例，是 global context，代码其他地方有用到，比如[这里](https://github.com/luoyetx/mini-caffe/blob/master/src/layer.hpp#L269-L283)判断运行环境是 cpu 还是 gpu。不同线程创建 net 对象没有问题，net 对象本身并不是线程安全的，不能创建一个对象然后在多个线程里去调用 net 对象的方法。

**Comment by zhly0** [comment]
明白了,多谢!
