### ISSUE TITLE
android version : can not new a caffe::net

### ISSUE THREAD

**Issue by ligongzheng** [luoyetx/mini-caffe#55]
hello:
        I  builded a .so file which linked against  minicaffe of android version. And I also have written a JNI file. But when I invoke the JAVA class in android studio ,a error was occurred： 
        A/libc:Fatal signal 6 (SIGABRT),code -6 in aid 28981.
       I located the question in one sentence：caffe::Net net_ = new caffe::Net("..."). It seems like the  the caffe's construct function was not invoked at all. So I doubt the size of stack was overflow or the program was failed to link against the libcaffe.so. 
      Could you give me some advice ? Thank you a lot !

**Comment by luoyetx** [comment]
@ligongzheng Did you compile your jni file successfully? Please take a look at [jni.c](https://github.com/luoyetx/mini-caffe/blob/master/src/jni/jni.c), this file use C interface. If you compile another C++ file, you should link the `libcaffe.so` file and generate another *.so file.

**Comment by ligongzheng** [comment]
I have figure it out. I use temp file( mkstemp ) in my code but android does not support it. Even I change the temp dir from /tmp to /data/lcoal/tmp. 
Thank you a lot !
