### ISSUE TITLE
caffe.LayerParameter has no field named"permute_param"

### ISSUE THREAD

**Issue by kingvision** [luoyetx/mini-caffe#57]
Hi:
    用mini-caffe编译mobile-ssd时，遇到“caffe.LayerParameter has no field named"permute_param"错误，
请问怎么修改？

谢谢

**Comment by luoyetx** [comment]
是不是用了某种 layer mini-caffe 不支持，这个可以自己添加layer

**Comment by luoyetx** [comment]
This problem should be solve after #69 merged.
