### ISSUE TITLE
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 7007:16: Message type "caffe.LayerParameter" has no field named "python_param".

### ISSUE THREAD

**Issue by jinfagang** [luoyetx/mini-caffe#59]
Successfully built rfc executable file, but when runing throw this error. What is this about?

**Comment by luoyetx** [comment]
mini caffe doesn't support Python layer. But the layers used by `rfcn` are all implemented in C++ and CUDA. Please use the [prototxt](https://github.com/luoyetx/mini-caffe/blob/master/example/models/r-fcn/test_agnostic.prototxt) file for rfcn in this repo.

**Comment by jinfagang** [comment]
Yet another error appears:

```
mini-caffe/src/net.cpp:205: Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1
terminate called after throwing an instance of 'caffe::Error'
  what():  [09:03:21] /home/jintian/Documents/mini-caffe/src/net.cpp:205: Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1

```

How?

**Comment by luoyetx** [comment]
your caffemodel's conv1 layer doesn't have bias term?

**Comment by jinfagang** [comment]
I download model from py-R-FCN repo, trained on coco with resnet50, I changed some rfcn model all have this error:

```
Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1
terminate called after throwing an instance of 'caffe::Error'

```

Did you train your model with your own caffe? Let me download yours and have a try.

**Comment by luoyetx** [comment]
I didn't train the model, I use resnet50_rfcn_final.caffemodel.

**Comment by 121786404** [comment]
这个问题 没有解决啊，https://1drv.ms/u/s!AoN7vygOjLIQqiZEmKSodg7UudD4
从这个地方下载的caffemodel
@luoyetx   模型没有问题吧
