### ISSUE TITLE
Why not use page-locked host memory for cpu blobs?

### ISSUE THREAD

**Issue by yszheda** [luoyetx/mini-caffe#74]
Hello,
Generally, page-locked host memory has higher bandwidth than pageable host memory when transferring between CPU and GPU.  However, in the current implementation of `SyncedMemory`, host memory is allocated as pageable. Is there any reason for not using page-locked host memory? Thank you!

page-locked host memory references:
* [CUDA C Programming Guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#page-locked-host-memory)
* [How to Optimize Data Transfers in CUDA C/C++](https://devblogs.nvidia.com/how-optimize-data-transfers-cuda-cc/)

**Comment by luoyetx** [comment]
@yszheda I'm not familiar with CUDA programming. I will try cudaMallocHost if `USE_CUDA=ON`.

**Comment by yszheda** [comment]
@luoyetx OK. I created a PR for that: https://github.com/luoyetx/mini-caffe/pull/75
