### ISSUE TITLE
There is a reshape related bug after "build with CUDA9 and cuDNN7"

### ISSUE THREAD

**Issue by HaoLiuHust** [luoyetx/mini-caffe#77]
After I updated the mini-caffe, there is a strange thing:
How to reproduce:
1. execute a forward with shape (2,c,w,h)
2. then run a forward with shape(1,c,w,h)
3. re-execute a forward with shape (2,c,w,h), note that the input is same with step 1, you will find the output is different with step 1, and if you re-execute step2, the output will change too.

I have tried to roll back it to "build with CUDA9 and cuDNN7", it will be ok, so this bug should be imported after this version, I will test other version if I have time.

@luoyetx

**Comment by luoyetx** [comment]
This issue is solved by #78
