### ISSUE TITLE
最新版本在程序运行example中程序退出时候报错，旧版本不存在此问题

### ISSUE THREAD

**Issue by xyt2008** [luoyetx/mini-caffe#81]
D:\mini-caffe\include\caffe/logging.hpp:211: [17:22:10] D:\mini-caffe\src\syncedmem.cpp:148: Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down

**Comment by yszheda** [comment]
这和caffe的[issue #6281](https://github.com/BVLC/caffe/issues/6281)是一个问题，具体可参考[《cudaErrorCudartUnloading问题排查及建议方案》](http://galoisplusplus.coding.me/blog/2018/05/22/cudaErrorCudartUnloading/)。
沿用 https://github.com/luoyetx/mini-caffe/blob/master/src/syncedmem.cpp#L308 的做法就可以了，我来提一个PR吧。

**Comment by taotaoyuhust** [comment]
> D:\mini-caffe\include\caffe/logging.hpp:211: [17:22:10] D:\mini-caffe\src\syncedmem.cpp:148: Check failed: error == cudaSuccess (29 vs. 0) driver shutting down

请问你解决了吗？
